# Generated by Django 4.2.5 on 2023-10-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NormalizeData", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="FacilityType",
            field=models.CharField(max_length=10),
        ),
    ]
