# Generated by Django 4.2.5 on 2023-10-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NormalizeData", "0002_alter_rawdata_facilitytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospitals",
            fields=[
                ("report_record", models.AutoField(primary_key=True, serialize=False)),
                ("provider_ccn", models.CharField(max_length=10, unique=True)),
                ("hospital_name", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state_code", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                ("county", models.CharField(max_length=255)),
                ("medicare_cbsa_number", models.CharField(max_length=10)),
                ("rural_versus_urban", models.CharField(max_length=50)),
                ("ccn_facility_type", models.CharField(max_length=255)),
                ("provider_type", models.CharField(max_length=255)),
                ("type_of_control", models.CharField(max_length=255)),
                ("fiscal_year_begin_date", models.DateField()),
                ("fiscal_year_end_date", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Hospitals",
            },
        ),
    ]
