# Generated by Django 4.2.5 on 2023-10-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("NormalizeData", "0003_hospitals"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalExpenses",
            fields=[
                (
                    "HospitalID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="NormalizeData.hospitals",
                    ),
                ),
                ("HospitalName", models.CharField(max_length=250)),
                ("CharityCareCost", models.IntegerField()),
                ("BadDebtExpense", models.IntegerField()),
                ("UncompasatedCaseCost", models.IntegerField()),
                ("TotalCost", models.IntegerField()),
                ("WageRelatedCostsCore", models.IntegerField()),
                ("WageRelatedCostsRHC_FQHC", models.IntegerField()),
                ("TotalSalaries", models.IntegerField()),
                ("ContractLabor", models.IntegerField()),
                ("WageCostsTeachingPhysicians", models.IntegerField()),
                ("WageCostInternAndResidents", models.IntegerField()),
                ("DepreciationCost", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "HospitalExpenses",
            },
        ),
    ]
