# Generated by Django 4.2.5 on 2023-10-02 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NormalizeData", "0004_hospitalexpenses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="CharityCareCost",
            new_name="CharityCost",
        ),
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="TotalSalaries",
            new_name="SalariesPayable",
        ),
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="UncompasatedCaseCost",
            new_name="UncompasatedCost",
        ),
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="WageCostInternAndResidents",
            new_name="WageCostInternResidents",
        ),
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="WageCostsTeachingPhysicians",
            new_name="WageCostsTeaching",
        ),
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="WageRelatedCostsRHC_FQHC",
            new_name="WageRelatedCostsRHC",
        ),
        migrations.RenameField(
            model_name="rawdata",
            old_name="CCN",
            new_name="HospitalID",
        ),
        migrations.RenameField(
            model_name="rawdata",
            old_name="WageRelatedCostsInternsResidents",
            new_name="WageCostInternResidents",
        ),
    ]
