# Generated by Django 4.2.5 on 2023-10-02 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "NormalizeData",
            "0005_rename_charitycarecost_hospitalexpenses_charitycost_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="WageCostInternResidents",
            new_name="WageRelatedCostInternResidents",
        ),
        migrations.RenameField(
            model_name="hospitalexpenses",
            old_name="WageCostsTeaching",
            new_name="WageRelatedCostsTeaching",
        ),
        migrations.RenameField(
            model_name="rawdata",
            old_name="WageCostInternResidents",
            new_name="WageRelatedCostInternResidents",
        ),
    ]
