# Generated by Django 4.2.5 on 2023-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "NormalizeData",
            "0006_rename_wagecostinternresidents_hospitalexpenses_wagerelatedcostinternresidents_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalWorkers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FTEEmployees", models.FloatField()),
                ("InternsResidents", models.FloatField()),
                ("ContractLabor", models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="ccn_facility_type",
            new_name="Address",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="medicare_cbsa_number",
            new_name="CBSANumber",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="city",
            new_name="City",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="county",
            new_name="ControlType",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="hospital_name",
            new_name="County",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="provider_type",
            new_name="FacilityType",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="fiscal_year_begin_date",
            new_name="FiscalYearBegin",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="fiscal_year_end_date",
            new_name="FiscalYearEnd",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="provider_ccn",
            new_name="HospitalID",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="street_address",
            new_name="HospitalName",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="type_of_control",
            new_name="ProviderType",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="rural_versus_urban",
            new_name="RuralUrban",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="state_code",
            new_name="StateCode",
        ),
        migrations.RenameField(
            model_name="hospitals",
            old_name="zip_code",
            new_name="ZipCode",
        ),
    ]
