# Generated by Django 4.2.5 on 2023-10-02 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NormalizeData", "0007_hospitalworkers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitals",
            old_name="County",
            new_name="Country",
        ),
        migrations.RenameField(
            model_name="rawdata",
            old_name="County",
            new_name="Country",
        ),
    ]
