# Generated by Django 4.2.5 on 2023-09-30 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_rawdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RawData",
        ),
    ]
